[phases.setup]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/23.11.tar.gz"

[phases.install]
aptPkgs = [
  "libpango-1.0-0",
  "libpangocairo-1.0-0",
  "libcairo2",
  "libgdk-pixbuf2.0-0",
  "libffi-dev",
  "libgobject-2.0-0",
  "libglib2.0-0"
]

[phases.build]
cmds = ["pip install -r requirements.txt"]
