# Generated by Django 5.0.1 on 2025-06-14 17:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="congelado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.IntegerField()),
                ("caso", models.CharField(blank=True, max_length=100, null=True)),
                ("tag", models.CharField(max_length=100)),
                ("descripcion_de_equipo", models.CharField(max_length=100)),
                ("Descripcion_del_fallo", models.CharField(max_length=100)),
                ("personal", models.CharField(max_length=80)),
                ("fecha_de_inicio", models.DateField()),
                ("especialidad", models.CharField(max_length=80)),
                ("empresa", models.CharField(max_length=80)),
                ("turno", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Herramienta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Informe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caso",
                    models.CharField(
                        choices=[
                            ("1", "Orden y Limpieza"),
                            ("2", "Retiro de OTs - Repuestos"),
                            ("3", "Creación de OTs"),
                            ("4", "Abastecimiento Pañol"),
                            ("5", "Carga de Repuestos"),
                            ("6", "Recepción e Izaje de Piezas Mecánicas"),
                        ],
                        max_length=1,
                    ),
                ),
                ("area", models.CharField(max_length=100)),
                ("hora_inicio", models.TimeField()),
                ("hora_culm", models.TimeField()),
                ("descripcion", models.TextField()),
                ("fecha", models.DateField()),
                (
                    "imagen_antes",
                    models.ImageField(blank=True, null=True, upload_to="anexos/"),
                ),
                (
                    "imagen_despues",
                    models.ImageField(blank=True, null=True, upload_to="anexos/"),
                ),
                ("ots_generadas", models.TextField(blank=True, null=True)),
                ("ot_panol", models.TextField(blank=True, null=True)),
                ("ots_cargadas", models.TextField(blank=True, null=True)),
                ("piezas", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Obrero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Repuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("cantidad", models.PositiveIntegerField()),
                ("ubicacion", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImagenInforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ot", models.CharField(max_length=100, verbose_name="N° OT o Dato")),
                ("imagen", models.ImageField(upload_to="anexos/")),
                (
                    "informe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="app.informe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=100, verbose_name="AREA")),
                (
                    "fecha_pedido",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "codigo_unico",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "compañia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pedido",
                        to="app.empresa",
                        verbose_name="EMPRESA",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.obrero"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PedidoInsumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(verbose_name="CANTIDAD")),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Área específica"
                    ),
                ),
                (
                    "insumos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.material",
                        verbose_name="INSUMO",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.pedido"
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.obrero",
                        verbose_name="Obrero asignado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENTREGADO", "Entregado"),
                            ("NO_ENTREGADO", "No Entregado"),
                        ],
                        default="NO_ENTREGADO",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                ("fecha_recepcion", models.DateField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestamo",
                        to="app.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "herramienta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestamo",
                        to="app.herramienta",
                        verbose_name="Herramienta",
                    ),
                ),
                (
                    "nombre_solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestamo",
                        to="app.obrero",
                        verbose_name="Obrero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RetiroRepuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("fecha_retiro", models.DateTimeField(auto_now_add=True)),
                ("area", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retirorepuesto",
                        to="app.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "repuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retirorepuesto",
                        to="app.repuesto",
                        verbose_name="REPUESTO",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retirorepuesto",
                        to="app.obrero",
                        verbose_name="Obrero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Trabajador",
                        to="app.empresa",
                        verbose_name="empresa o grupo",
                    ),
                ),
                (
                    "nombre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Trabajador",
                        to="app.obrero",
                        verbose_name="Obrero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utilesaseo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("ENERO", "ENERO"),
                            ("FEBRERO", "FEBRERO"),
                            ("MARZO", "MARZO"),
                            ("ABRIL", "ABRIL"),
                            ("MAYO", "MAYO"),
                            ("JUNIO", "JUNIO"),
                            ("JULIO", "JULIO"),
                            ("AGOSTO", "AGOSTO"),
                            ("SEPTIEMBRE", "SEPTIEMBRE"),
                            ("OCTUBRE", "OCTUBRE"),
                            ("NOVIEMBRE", "NOVIEMBRE"),
                            ("DICIEMBRE", "DICIEMBRE"),
                        ],
                        default="ENERO",
                        max_length=20,
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                ("run", models.CharField(max_length=100)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilesaseo",
                        to="app.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "nombre_solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilesaseo",
                        to="app.obrero",
                        verbose_name="Obrero",
                    ),
                ),
                (
                    "productos",
                    models.ManyToManyField(
                        related_name="utilesaseos",
                        to="app.producto",
                        verbose_name="Producto",
                    ),
                ),
            ],
        ),
    ]
