# Generated by Django 5.0.1 on 2024-01-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirorepuesto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retirorepuesto', to='app.empresa', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='retirorepuesto',
            name='nombre_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retirorepuesto', to='app.obrero', verbose_name='Obrero'),
        ),
        migrations.AlterField(
            model_name='retirorepuesto',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retirorepuesto', to='app.repuesto', verbose_name='REPUESTO'),
        ),
    ]
