# Generated by Django 5.0.1 on 2025-06-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="numero_reporte",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
