# Generated by Django 5.0.1 on 2024-01-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_retirorepuesto_empresa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retirorepuesto',
            old_name='nombre_solicitante',
            new_name='trabajador',
        ),
    ]
