# Generated by Django 5.0.1 on 2025-05-14 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_pedidoinsumo_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="solicitante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.obrero"
            ),
        ),
        migrations.AlterField(
            model_name="pedidoinsumo",
            name="trabajador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.obrero",
                verbose_name="Obrero asignado",
            ),
        ),
    ]
