# Generated by Django 5.0.1 on 2025-06-15 21:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_pedido_numero_reporte"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportePDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                ("pedidos", models.ManyToManyField(to="app.pedido")),
            ],
        ),
    ]
