# Generated by Django 5.0.1 on 2025-06-15 21:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_reportepdf"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "generado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("pedidos", models.ManyToManyField(to="app.pedido")),
            ],
        ),
        migrations.DeleteModel(
            name="ReportePDF",
        ),
    ]
