# Generated by Django 5.0.1 on 2025-05-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_pedido_solicitante_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Informe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caso",
                    models.CharField(
                        choices=[
                            ("1", "Orden y Limpieza"),
                            ("2", "Retiro de OTs - Repuestos"),
                            ("3", "Creación de OTs"),
                            ("4", "Abastecimiento Pañol"),
                            ("5", "Carga de Repuestos"),
                            ("6", "Recepción e Izaje de Piezas Mecánicas"),
                        ],
                        max_length=1,
                    ),
                ),
                ("hora", models.TimeField()),
                ("tarea", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("desde", models.DateField(blank=True, null=True)),
                ("hasta", models.DateField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "imagen_antes",
                    models.ImageField(blank=True, null=True, upload_to="anexos/"),
                ),
                (
                    "imagen_despues",
                    models.ImageField(blank=True, null=True, upload_to="anexos/"),
                ),
            ],
        ),
    ]
