# Generated by Django 5.0.1 on 2024-02-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilesaseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('ENERO', 'ENERO'), ('FEBRERO', 'FEBRERO'), ('MARZO', 'MARZO'), ('ABRIL', 'ABRIL'), ('MAYO', 'MAYO'), ('JUNIO', 'JUNIO'), ('JULIO', 'JULIO'), ('AGOSTO', 'AGOSTO'), ('SEPTIEMBRE', 'SEPTIEMBRE'), ('NOVIEMBRE', 'NOVIEMBRE'), ('DICIEMBRE', 'DICIEMBRE')], default='ENERO', max_length=20)),
                ('producto', models.CharField(choices=[('OMO', 'OMO'), ('JABON', 'JABON'), ('CONFORT', 'CONFORT')], default='OMO', max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('run', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilesaseo', to='app.empresa', verbose_name='empresa')),
                ('nombre_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilesaseo', to='app.obrero', verbose_name='Obrero')),
            ],
        ),
    ]
