# Generated by Django 5.0.1 on 2025-05-29 17:49

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_informe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informe',
            old_name='hora',
            new_name='hora_culm',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='desde',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='hasta',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='tarea',
        ),
        migrations.AddField(
            model_name='informe',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2025, 5, 29, 17, 49, 3, 733384, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
