# Generated by Django 5.0.1 on 2025-06-15 21:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_reportepedido_delete_reportepdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportepedido",
            name="fecha",
        ),
        migrations.AddField(
            model_name="reportepedido",
            name="fecha_generacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="reportepedido",
            name="generado_por",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="reportepedido",
            name="pedidos",
            field=models.ManyToManyField(related_name="reportes", to="app.pedido"),
        ),
    ]
