# Generated by Django 5.0.1 on 2025-06-15 21:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_reportepedido_fecha_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportepedido",
            name="codigo",
        ),
        migrations.AddField(
            model_name="reportepedido",
            name="codigo_reporte",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
