# Generated by Django 5.0.1 on 2025-05-29 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_hora_informe_hora_culm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='area',
            field=models.CharField(default=datetime.datetime(2025, 5, 29, 19, 33, 48, 593117, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
