# Generated by Django 5.0.1 on 2025-06-15 21:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_reportepedido_codigo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportepedido",
            name="codigo_reporte",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
