# Generated by Django 5.0.1 on 2025-05-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_informe_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='ots_retiradas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
