# Generated by Django 5.0.1 on 2024-08-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_utilesaseo_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('OMO', 'OMO'), ('JABON', 'JABON'), ('CONFORT', 'CONFORT')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='utilesaseo',
            name='producto',
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='utilesaseo',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='utilesaseos', to='app.producto'),
        ),
    ]
