# Generated by Django 5.0.1 on 2025-05-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_informe_ots_retiradas'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='ots_generadas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
