# Generated by Django 5.0.1 on 2025-05-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_informe_ots_generadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='ot_panol',
            field=models.TextField(blank=True, null=True),
        ),
    ]
