# Generated by Django 5.0.1 on 2024-08-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_producto_nombre_alter_utilesaseo_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='congelado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('prioridad', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=30)),
                ('descripcion_de_equipo', models.CharField(max_length=30)),
                ('Descripcion_del_fallo', models.CharField(max_length=30)),
                ('personal', models.CharField(max_length=80)),
                ('fecha_de_inicio', models.DateField()),
                ('especialidad', models.CharField(max_length=80)),
                ('empresa', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
