# Generated by Django 5.0.1 on 2025-06-17 18:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_reporteinsumo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetallePrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_entrega",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("observacion", models.TextField(blank=True, null=True)),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.material"
                    ),
                ),
                (
                    "prestamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.prestamo"
                    ),
                ),
            ],
        ),
    ]
