# Generated by Django 5.0.1 on 2025-06-25 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_detalleprestamo"),
    ]

    operations = [
        migrations.AddField(
            model_name="retirorepuesto",
            name="fecha_generacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="retirorepuesto",
            name="numero_reporte",
            field=models.PositiveIntegerField(default=1000, unique=True),
        ),
    ]
