# Generated by Django 5.0.1 on 2024-08-26 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_congelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='congelado',
            name='turno',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
