# Generated by Django 5.0.1 on 2025-05-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_informe_ots_cargadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='piezas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
