# Generated by Django 5.0.1 on 2024-08-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_congelado_turno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='congelado',
            old_name='prioridad',
            new_name='caso',
        ),
    ]
