# Generated by Django 5.0.1 on 2025-06-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_retirorepuesto_fecha_generacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retirorepuesto",
            name="numero_reporte",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
