# Generated by Django 5.0.1 on 2025-06-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_retirorepuesto_numero_reporte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retirorepuesto",
            name="numero_reporte",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
