# Generated by Django 5.0.1 on 2024-08-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_prioridad_congelado_caso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congelado',
            name='Descripcion_del_fallo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='congelado',
            name='caso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='congelado',
            name='descripcion_de_equipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='congelado',
            name='tag',
            field=models.CharField(max_length=100),
        ),
    ]
