# Generated by Django 5.0.1 on 2025-06-02 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_informe_piezas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot', models.CharField(max_length=100, verbose_name='N° OT o Dato')),
                ('imagen', models.ImageField(upload_to='anexos/')),
                ('tipo', models.CharField(choices=[('antes', 'Antes'), ('despues', 'Después')], default='antes', max_length=20)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app.informe')),
            ],
        ),
    ]
