# Generated by Django 5.0.1 on 2025-06-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_imageninforme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageninforme',
            name='tipo',
        ),
    ]
