# Generated by Django 5.0.1 on 2025-06-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_retirorepuesto_numero_reporte"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReporteRetiroRepuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_reporte", models.CharField(max_length=30, unique=True)),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                ("filtro", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="retirorepuesto",
            name="fecha_generacion",
        ),
        migrations.RemoveField(
            model_name="retirorepuesto",
            name="numero_reporte",
        ),
    ]
