# Generated by Django 5.0.1 on 2025-06-02 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_imageninforme_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='ots_retiradas',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
