# Generated by Django 5.0.1 on 2025-06-25 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_reporteretirorepuesto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporteretirorepuesto",
            name="trabajador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.obrero",
            ),
        ),
    ]
