# Generated by Django 5.0.1 on 2025-06-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_informe_ots_retiradas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='ots_retiradas',
        ),
    ]
