# Generated by Django 5.0.1 on 2025-06-25 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_reporteretirorepuesto_trabajador"),
    ]

    operations = [
        migrations.AddField(
            model_name="retirorepuesto",
            name="reporte",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retiros",
                to="app.reporteretirorepuesto",
            ),
        ),
    ]
