# Generated by Django 5.0.1 on 2025-06-26 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_retirorepuesto_reporte"),
    ]

    operations = [
        migrations.CreateModel(
            name="UtilAseoDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.producto"
                    ),
                ),
                (
                    "utilesaseo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="app.utilesaseo",
                    ),
                ),
            ],
        ),
    ]
