# Generated by Django 5.0.1 on 2025-06-26 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_utilaseodetalle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilesaseo",
            name="cantidad",
        ),
    ]
