# Generated by Django 5.0.1 on 2025-06-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_remove_utilesaseo_cantidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilesaseo",
            name="numero_reporte",
            field=models.CharField(
                blank=True, max_length=100000, null=True, unique=True
            ),
        ),
    ]
