# Generated by Django 5.0.1 on 2025-06-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_utilesaseo_numero_reporte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilesaseo",
            name="numero_reporte",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
