# Generated by Django 5.0.1 on 2025-06-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_utilesaseo_numero_reporte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilesaseo",
            name="numero_reporte",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
