# Generated by Django 5.0.1 on 2025-06-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_utilesaseo_numero_reporte"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificacionInforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_reporte", models.CharField(max_length=30, unique=True)),
                ("fecha", models.DateField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
